//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.28 at 05:31:44 PM CDT 
//


package com.creatures.xml.pokemon;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.creatures.xml.pokemon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.creatures.xml.pokemon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PokemonMovesRequest }
     * 
     */
    public PokemonMovesRequest createPokemonMovesRequest() {
        return new PokemonMovesRequest();
    }

    /**
     * Create an instance of {@link PokemonDetailsRequest }
     * 
     */
    public PokemonDetailsRequest createPokemonDetailsRequest() {
        return new PokemonDetailsRequest();
    }

    /**
     * Create an instance of {@link PokemonItemsRequest }
     * 
     */
    public PokemonItemsRequest createPokemonItemsRequest() {
        return new PokemonItemsRequest();
    }

    /**
     * Create an instance of {@link PokemonAbilitiesResponse }
     * 
     */
    public PokemonAbilitiesResponse createPokemonAbilitiesResponse() {
        return new PokemonAbilitiesResponse();
    }

    /**
     * Create an instance of {@link PokemonAbilities }
     * 
     */
    public PokemonAbilities createPokemonAbilities() {
        return new PokemonAbilities();
    }

    /**
     * Create an instance of {@link PokemonItemsResponse }
     * 
     */
    public PokemonItemsResponse createPokemonItemsResponse() {
        return new PokemonItemsResponse();
    }

    /**
     * Create an instance of {@link PokemonItems }
     * 
     */
    public PokemonItems createPokemonItems() {
        return new PokemonItems();
    }

    /**
     * Create an instance of {@link PokemonAbilitiesRequest }
     * 
     */
    public PokemonAbilitiesRequest createPokemonAbilitiesRequest() {
        return new PokemonAbilitiesRequest();
    }

    /**
     * Create an instance of {@link PokemonDetailsResponse }
     * 
     */
    public PokemonDetailsResponse createPokemonDetailsResponse() {
        return new PokemonDetailsResponse();
    }

    /**
     * Create an instance of {@link Pokemon }
     * 
     */
    public Pokemon createPokemon() {
        return new Pokemon();
    }

    /**
     * Create an instance of {@link PokemonMovesResponse }
     * 
     */
    public PokemonMovesResponse createPokemonMovesResponse() {
        return new PokemonMovesResponse();
    }

    /**
     * Create an instance of {@link PokemonMoves }
     * 
     */
    public PokemonMoves createPokemonMoves() {
        return new PokemonMoves();
    }

    /**
     * Create an instance of {@link Ability }
     * 
     */
    public Ability createAbility() {
        return new Ability();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Move }
     * 
     */
    public Move createMove() {
        return new Move();
    }

    /**
     * Create an instance of {@link PokemonBasedExp }
     * 
     */
    public PokemonBasedExp createPokemonBasedExp() {
        return new PokemonBasedExp();
    }

}
