//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.28 at 05:31:44 PM CDT 
//


package com.creatures.xml.pokemon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pokemon" type="{http://www.creatures.com/xml/pokemon}Pokemon"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pokemon"
})
@XmlRootElement(name = "PokemonDetailsResponse")
public class PokemonDetailsResponse {

    @XmlElement(name = "Pokemon", required = true)
    protected Pokemon pokemon;

    /**
     * Gets the value of the pokemon property.
     * 
     * @return
     *     possible object is
     *     {@link Pokemon }
     *     
     */
    public Pokemon getPokemon() {
        return pokemon;
    }

    /**
     * Sets the value of the pokemon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pokemon }
     *     
     */
    public void setPokemon(Pokemon value) {
        this.pokemon = value;
    }

}
